In [1]:
print("hi")

hi

In [2]:
import pandas as pd
import numpy as np
data= pd.read_csv("data.csv")
data.head()

,Brand,Model_Name,Year_of_Launch,Purchase_Price_INR,Predicted_Current_Value_INR
0,OnePlus,OnePlus 10R,2022,88004,28111
1,OnePlus,OnePlus 8,2018,105467,7853
2,Oppo,Oppo Reno 6,2023,69351,32978
3,Nokia,Nokia G20,2023,58872,24598
4,Motorola,Moto Edge 20,2019,20315,-818

In [7]:
import sys
print(sys.executable)

/usr/local/anaconda3/envs/resale/bin/python

In [3]:
data.describe()

       Year_of_Launch  Purchase_Price_INR  Predicted_Current_Value_INR
count   100000.000000       100000.000000                100000.000000
mean      2021.004320        68549.386160                 18804.695950
std          2.001755        35384.462317                 18667.262123
min       2018.000000         7001.000000                 -2495.000000
25%       2019.000000        38075.000000                  5702.750000
50%       2021.000000        68618.500000                 11829.000000
75%       2023.000000        99034.000000                 25784.250000
max       2024.000000       129998.000000                 89771.000000

In [5]:
data.info

<bound method DataFrame.info of           Brand     Model_Name  Year_of_Launch  Purchase_Price_INR  \
0       OnePlus    OnePlus 10R            2022               88004
1       OnePlus      OnePlus 8            2018              105467
2          Oppo    Oppo Reno 6            2023               69351
3         Nokia      Nokia G20            2023               58872
4      Motorola   Moto Edge 20            2019               20315
...         ...            ...             ...                 ...
99995    Xiaomi  Redmi Note 11            2024               69326
99996  Motorola   Moto Edge 20            2024              102852
99997   Samsung     Galaxy S20            2018               40139
99998      Vivo       Vivo X60            2018               69082
99999    Realme       Realme 8            2018               33680

       Predicted_Current_Value_INR
0                            28111
1                             7853
2                            32978
3                            24598
4                             -818
...                            ...
99995                        44263
99996                        70310
99997                         3788
99998                         4835
99999                         3506

[100000 rows x 5 columns]>

In [6]:
data.isnull().sum()

Brand                          0
Model_Name                     0
Year_of_Launch                 0
Purchase_Price_INR             0
Predicted_Current_Value_INR    0
dtype: int64

In [7]:
# df should be connverted into dict before we push it to mongoDB
data = data.to_dict("records")

In [ ]:
DB_NAME = "mobile_resale_value"
COLLECTION_NAME = "mobile_data" 
CONNECTION_URL = "mongodb+srv://rahultomer218_db_user:q9d4a7OloKRw6imV@cluster0.n9wqubk.mongodb.net/?appName=Cluster0"

In [11]:
import pymongo

CONNECTION_URL = "your_mongodb_connection_string"
DB_NAME = "mobile_resale"
COLLECTION_NAME = "mobile_data"

client = pymongo.MongoClient(CONNECTION_URL)
db = client[DB_NAME]
collection = db[COLLECTION_NAME]

print("Connected to MongoDB successfully!")

Connected to MongoDB successfully!

In [13]:
rec = collection.insert_many(data)

ServerSelectionTimeoutError: your_mongodb_connection_string:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69eef13d60281af4e2680405, topology_type: Unknown, servers: [<ServerDescription ('your_mongodb_connection_string', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('your_mongodb_connection_string:27017: [Errno 8] nodename nor servname provided, or not known (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>